all: make_base make_dropbox make_blackhole

make_base:
	@make -C base

make_dropbox:
	@make -C dropbox

make_blackhole:
	@make -C blackhole

clean:
	@make -C base clean
	@make -C dropbox clean
	@make -C blackhole clean
